clone_depth: 1
version: 4.1.3.{build}
image: Visual Studio 2017

services:
  - mssql2017
  - mongodb 

matrix:
  fast_finish: false


environment:
  resizer_test_mongo_db: mongodb://localhost:27017/resizer2

  can_access_secure_vars: 
    secure: VeSU4qx0Ux6Wu4ZM9f+TTg==

  fb_s3_bucket: "resizer-nightlies"
  fb_s3_id:
    secure: FTa/u2Pi/dXMCfgDw5iC5pIUTtTjLdhvg8PA8nRyPJw=
  fb_s3_key:
    secure: 7JfttWZLof6WQc0DwIlvF3Bh2HaF7v56vYgmz82YcWJrcsCENHIxAxnI/nL+zwO9
  fb_s3_rel_bucket: "resizer-releases"
  fb_s3_rel_id:
    secure: zjU5gXrbdMergGCt2cE019dyeBfWhiwZkLY14PxPxDM=
  fb_s3_rel_key:
    secure: r5+d1DGmuXmorxDTfzh1EQu3ocWIlgXcw0MIZ+dDQiQewaHewV6GRfqPlgYxRtG2

  matrix: 
  #This build may have license key enforcemenet on certain plugins
  - license_keys: true
    #Nuget target feed for nightlies
    fb_nuget_url: https://www.myget.org/F/imazen-nightlies/
    fb_nuget_key:
      secure:  bd9FjQP6MRkmDIkwOW1uPwlg/baX8ug67VbBLP55B158zorSJqpHAFrENVuVhw3/
    #nuget.org for releases
    fb_nuget_rel_url: https://nuget.org/api/v2/package
    fb_nuget_rel_key:
      secure: AZ2O7RR0HT/kX2M6xcLNw03grcPQbVRljPdbuh8v5k9rKeacvSrgARZ/k4UZqC17


    fb_pub_url: https://s3.amazonaws.com/imazen-nightlies

    fb_imageserver_repo: github.com/imazen/resizer-images.git
    fb_imageserver_path: resizer-images
    fb_imageserver_branch: develop
    # should be set to master when resizer-images is updated
    fb_imageserver_rel_branch: master

    imageserver_user: imazen-bot
    imageserver_mail:
      secure: jM22KTaopLkZQS0SMkU+g9O9AYH6grGoN0v67bLYpUQ=
    imageserver_token:
      secure: koPsP9KtdkZ+WFJFfKiet2wKd3yI53jryA5QOHQLpPLbid0AgjIjY093+pPtwBid

  #This build has no license key enforcement. For verified AGPL and paid customers.
  - license_keys: false
    #Nuget target feed for nightlies
    fb_nuget_url: 
      secure: N/C7Edcuu/hVDDGZnp7lhJLYNUvT2HCrUA0l6axJZWmTV/v1V9xePzIpgDGQ3T78d1g3MDpvbRJ/ioMxFCy4XA==
    fb_nuget_key:
      secure: bd9FjQP6MRkmDIkwOW1uPwlg/baX8ug67VbBLP55B158zorSJqpHAFrENVuVhw3/
    #Nuget target feed for releases
    fb_nuget_rel_url:
      secure: N/C7Edcuu/hVDDGZnp7lhIG0giibMSvdxTrHwmgfi0Ro9cuoOGWXOkjgkMaFq+uSiQojoQtDqNDGfoVRwqZ0Lw==
    fb_nuget_rel_key:
      secure: bd9FjQP6MRkmDIkwOW1uPwlg/baX8ug67VbBLP55B158zorSJqpHAFrENVuVhw3/

    fb_pub_url: https://s3.amazonaws.com/imazen-nightlies


before_build:

  # add imageserver key
  - git config --global push.default simple
  - git config --global credential.helper wincred
  - git config --global user.name "%imageserver_user%"
  - git config --global user.email "%imageserver_mail%"
  - if /I "%APPVEYOR_REPO_TAG"=="True" set fb_imageserver_branch=fb_imageserver_rel_branch
  - if /I NOT "%imageserver_token%"=="" git clone --depth 1 --branch %fb_imageserver_branch% https://%imageserver_user%:%imageserver_token%@%fb_imageserver_repo% Tools\%fb_imageserver_path%


  - if "%license_keys%"=="false" copy  /Y Plugins\LicenseVerifier\LicensingOff.cs Plugins\LicenseVerifier\LicensingOn.cs

build_script:
  - cd Tools
  - builder prepare
  - SET BUILD_TASK=do_anonymous
  - if /I NOT "%can_access_secure_vars%"=="" SET BUILD_TASK=do_all
  - builder %BUILD_TASK%
  - cd ..

after_build:
  - ps: Get-ChildItem .\Releases\*.zip | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

test: off
